export const UCLA_BLUE_RGB = "39, 116, 174";
export const UCLA_DARKER_BLUE_RGB = "0, 85, 135";
export const UCLA_LIGHTER_BLUE_RGB = "139, 184, 232";
export const UCLA_LIGHTEST_BLUE_RGB = "218, 235, 254";

export const DONORS = [
  "James Chen",
  "Ashley Sun",
  "Mark Gross",
  "William Yao",
  "Olive Long",
  "Allison Li",
  "Tian Ouyang",
  "Sammy Fesili",
  "Khang Nguyen Le Tuan",
  "Casey T",
  "Gabriel Soulman",
  "Manseej Khatri",
  "Christopher Milan",
  "Kevin Tran",
  "Mallesh Dhamodran",
  "Rory Kien",
  "Samuel Leistiko",
  "Preston Rooker",
  "Cassidy Ott",
  "Alex Rojas",
  "Aiden Gresham",
  "Erin Su",
  "Tiffany Chen",
  "Gage Green",
  "Akane Shimoyoshi",
  "Alex Lebow",
  "Xiaoyang Liu",
  "Rahul Sathish",
  "James Snyder",
  "Hayley Vu",
  "Rujula Rao",
  "Brandon Zhao",
  "Ashley Tohm",
  "Ryan Schoenburg",
  "Ryan Zdral",
  "Jason M",
  "Joshua Lim",
  "Elaine Tran",
  "Jiexuan Fang",
  "A O",
  "Alec Machlis",
  "Ryan Chow",
  "Michelle Kim",
  "Natalie Brown",
  "Michelle Sun",
  "Kevin Tang",
];
